AWSTemplateFormatVersion: "2010-09-09"
Description: Launch WordPress via Auto Scaling Group (always 1 instance) from ARM64 golden AMI, with public IPv4 on launch

Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Default: ami-0138367b8c6c73669
    Description: AMI ID (km-simpli-wp-ami) - ARM64

  InstanceType:
    Type: String
    Default: t4g.micro
    AllowedValues:
      - t4g.micro
    Description: EC2 instance type (ARM64)

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: km-ec2-key
    Description: Existing EC2 KeyPair name for SSH access

  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: vpc-0b925d4fac7b3861e
    Description: VPC (informational; not required when using SubnetIds + SG)

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Default: subnet-04856bc381de403b2
    Description: Subnets for the ASG (use 2 public subnets in different AZs for best resilience)

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0c3996629c834fa0f
    Description: Existing Security Group ID

Resources:
  WordpressLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName

        # Force a public IP at launch
        NetworkInterfaces:
          - DeviceIndex: 0
            AssociatePublicIpAddress: true
            Groups:
              - !Ref SecurityGroupId

        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e
            systemctl enable httpd mariadb || true
            systemctl restart mariadb || true
            systemctl restart httpd || true

        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: km-simpli-wp

  WordpressAsg:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      VPCZoneIdentifier: !Ref SubnetIds

      HealthCheckType: EC2
      HealthCheckGracePeriod: 180

      LaunchTemplate:
        LaunchTemplateId: !Ref WordpressLaunchTemplate
        Version: !GetAtt WordpressLaunchTemplate.LatestVersionNumber

      Tags:
        - Key: Name
          Value: km-simpli-wp
          PropagateAtLaunch: true

Outputs:
  AsgName:
    Description: Auto Scaling Group name
    Value: !Ref WordpressAsg
